module TankLocationsHelper

	def get_neighborhood_names
		neighborhood_names = [
			
			"Grand Boulevard", 
			"Printers Row", 
			"United Center", 
			"Sheffield & DePaul", 
			"Humboldt Park", 
			"Garfield Park", 
			"North Lawndale", 
			"Little Village", 
			"Armour Square", 
			"Avalon Park", 
			"Burnside", 
			"Hermosa", 
			"Avondale", 
			"Logan Square", 
			"Calumet Heights", 
			"East Side", 
			"West Pullman", 
			"Garfield Ridge", 
			"New City", 
			"Englewood", 
			"Grand Crossing", 
			"Ashburn", 
			"Mount Greenwood", 
			"Morgan Park", 
			"O'Hare", 
			"Jackson Park", 
			"Loop", 
			"Pullman", 
			"Riverdale", 
			"Hegewisch", 
			"Greektown", 
			"Douglas", 
			"Museum Campus", 
			"Edgewater", 
			"Lake View", 
			"Lincoln Park", 
			"Magnificent Mile", 
			"Lincoln Square", 
			"Oakland", 
			"Grant Park", 
			"West Loop", 
			"Fuller Park", 
			"Andersonville", 
			"Woodlawn", 
			"Portage Park", 
			"Rush & Division", 
			"Little Italy, UIC", 
			"Kenwood", 
			"Rogers Park", 
			"Jefferson Park", 
			"Sauganash,Forest Glen", 
			"North Park", 
			"Albany Park", 
			"Irving Park", 
			"Dunning", 
			"West Ridge", 
			"Uptown", 
			"Norwood Park", 
			"Streeterville", 
			"South Shore", 
			"Chatham", 
			"South Chicago", 
			"Roseland", 
			"North Center", 
			"South Deering", 
			"Washington Park", 
			"Millenium Park", 
			"Near South Side", 
			"Chinatown", 
			"Chicago Lawn", 
			"Auburn Gresham", 
			"Beverly", 
			"Washington Heights", 
			"Edison Park", 
			"Hyde Park", 
			"Bucktown", 
			"Lower West Side", 
			"Wrigleyville", 
			"Archer Heights", 
			"Brighton Park", 
			"Mckinley Park", 
			"East Village", 
			"West Town", 
			"Bridgeport", 
			"West Elsdon", 
			"Gage Park", 
			"Clearing", 
			"West Lawn", 
			"Wicker Park", 
			"Ukrainian Village", 
			"Galewood", 
			"Montclare", 
			"Old Town", 
			"Belmont Cragin", 
			"Austin", 
			"Gold Coast", 
			"Boystown", 
			"River North"
		]

	end 
end

